# 3번째 과제#



In [6]:
#L=[1, 2, 3, 4, 5]일 때 다음 각 문장을 수행한 후의 결과를 보고 납득할 만한 이유를 설명하시오. 

L=[1, 2, 3, 4, 5]

L[1:3] =[100]
print L


[1, 100, 4, 5]


리스트 L에서 1부터 3까지에 100을 저장 하는 것으로 2,3 대신 100을 넣어 [1, 100, 4, 5] 가 출력됩니다.

In [45]:
L=[1, 2, 3, 4, 5]

L[1:3] = [(100)]

print L

[1, 100, 4, 5]


리스트 L에서 1부터 3까지에 100을 저장 하는 것으로 2,3 대신 리스트로 100을 넣어 [1, 100, 4, 5] 가 출력됩니다.(하나의 튜플을 넣어 정수 처리 되었습니다.)

In [37]:
L=[1, 2, 3, 4, 5]
L[1:3] = 100
print L

TypeError: can only assign an iterable

리스트 L에서 1:3이면 인덱스 1과2 두곳을 가르키는데 한가지 정수만을 저장하려 하여 오류가 납니다. 이때는 리스트로 바꾸어 주거나 정수 하나를 더 써주면 저장이 가능합니다.

In [38]:
L=[1, 2, 3, 4, 5]
L[1:3] = (100)
print L

TypeError: can only assign an iterable

리스트 L에서 1:3이면 인덱스 1과2 두곳을 가르키는데 한가지 튜플만을 저장하려 하여 오류가 납니다. 이때는 리스트로 바꾸어 주거나 튜플 하나를 더 써주면 저장이 가능합니다.

In [39]:
L=[1, 2, 3, 4, 5]
L[1:3] = (100, 101, 102)
print L

[1, 100, 101, 102, 4, 5]


리스트 L에서 1부터 3까지 즉 2,3 대신에 튜플 100 10.1 102를 저장 하여 [1, 100, 101, 102, 4, 5] 이출력됩니다. 

In [41]:
L=[1, 2, 3, 4, 5]
L[1:3] = [100, 101, 102]
print L

[1, 100, 101, 102, 4, 5]


리스트 L에서 1부터 3까지 즉 2,3 대신에 리스트 100 10.1 102를 저장 하여 [1, 100, 101, 102, 4, 5] 이출력됩니다. 

In [42]:
L=[1, 2, 3, 4, 5]
L[1:3] = [(100, 101, 102)]
print L

[1, (100, 101, 102), 4, 5]


리스트 L에서 1부터 3까지 즉 2,3 대신에 튜플 (100 10.1 102)을 저장 하여 [1,(100, 101, 102), 4, 5] 이출력됩니다.(하나의 튜플만 저장하면 정수 처리 되지만 두개 이상부터는 튜플로 저장됩니다.)

In [49]:
L=[1, 2, 3, 4, 5]
L[1:3] = [[100, 101, 102]]
print L

[1, [100, 101, 102], 4, 5]


리스트 L에서 1부터 3까지 즉 2,3 대신에 리스트 [100 10.1 102]를 저장 하여 [1,[100, 101, 102], 4, 5] 이 출력 됩니다.(하나의 리스트만 저장하면 정수 처리 되지만 두개 이상부터는 리스트로 저장됩니다.) 

In [77]:
#문자열 S = 'Hello World and Python'에 대해 다음 요구사항에 대한 Python 코드를 제시하시오. 
s='Hello World and Python'
L=s.split()
L.reverse()
s2=(" ".join(L))
print s2
s2=s2.split()
s2=("".join(L))
print s2

Python and World Hello
PythonandWorldHello


문자열 s에 'Hello World and Python'을 저장 하여 줍니다. split()을 사용 하여 단어 별로 나누어 주고 이를 매소드 reverse()를 이용하여 단어들의 순서를 반대로 바꾸어 줍니다. 그 후 리스트를 문자열로 바꾸면서 한칸씩 띄워 주기위해 JOIN을 사용하여 앞에는 " "을 사용하여 한칸씩 띄어쓰기 해줍니다. 그 후 s2에 문자열로 저장 하여줍니다.
이 문자열을 다시 split()으로 나눈 후에 join()을 사용하여 다시 문자열로 s2에 저장하는데 이때 앞의 ""에 아무것도 넣지 않으면 단어는 모두 붙어서 나옵니다. 사실 문제에서 spilt()을 사용하라고 하여서 사용했지 이 코드를 주석처리 하여도 똑같은 결과가 출력됩니다.

In [1]:
'''다음 코드를 보고 물음에 답하시오.
a = [1, 2, 3]
b = a * 3
c = [a] * 3
print b
print c  '''

a = [1, 2, 3]
b = a * 3
c = [a] * 3
print b
print c

a[0]=0


print b
print c

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[0, 2, 3], [0, 2, 3], [0, 2, 3]]


b는 새로운 a를 3번 이어서 새로운 리스트 [1, 2, 3, 1, 2, 3, 1, 2, 3]를 가리키는 객체가 되었고 c는 a리스트를 3번을 가리켜 출력을 하도록 되어있습니다. 그러므로  a리스트의 값이 바뀌면 그대로 가리켜 바뀐 값을 3번 출력합니다

In [140]:
'''다음 문자열을 ':'을 기준으로 분리하여 리스트로 만들고 각 문자열의 좌우 공백을 제거하시오 (즉, 문자열 S에서 l을 만들어라) 
s = '  first star   :   second star   :    third star  '
l = ['first star', 'second star', 'third star']

1) for ~ in 문을 이용한 코드를 작성하시오. '''

s = '  first star   :   second star   :    third star  '
L=[]
n= len(s)
for i in range(n):
    L+=s[i]

L=''.join(L)
L=L.split(':')
for j in range(len(L)):
    L[j]=L[j].strip()
print L


['first star', 'second star', 'third star']


문자열 s를 선언한 후 리스트 L을 만들어줍니다. 그리고 0부터 문자열 크기만큼 모든 문자 하나 하나 for문을 써 리스트 L에 저장 하여 줍니다. 그리고 난 후 리스트 L을 join()을 사용하여 문자를 모두 연결 하여 줍니다. 그 후 split(‘:’)을 이용하여 :를 기준으로 리스트를 나누게 하여 줍니다. 그런 후 리스트에 포함된 원소들을 strip()을 사용하여 좌우 공백을 제거해 줍니다.


In [ ]:
#리스트 내포(list comprehension)를 이용한 코드를 작성하시오.

s = '  first star   :   second star   :    third star  '

n= len(s)
L=[s[i] for i in range(n) ]

L=''.join(L)
L=L.split(':')
for j in range(len(L)):
    L[j]=L[j].strip()
print L

모두 위의 방식과 동일하고 위에서는 리스트 L을 선언하고 아래에서 for문을 이용해 L에 하나하나 문자를 넣었지만 여기서는 리스트 내포를 이용하여 리스트 L을 선언과동시에 그안에서 for문을 사용해 s의 문자열 문자를 리스트 L에 저장하였습니다. 

In [5]:
'''다음과 같이 0보다 큰 정수 리스트 변수 list를 인자로 받는 함수 addall(list)와 addallodd(list)를 for ~ in 리터널과 리스트 내포 방식으로 
각각 제시하시오.
1) addall(list) 함수 (리스트 내의 모든 정수를 더하는 함수로서 해답으로는 for ~ in 리터럴과 리스트 내포 방식으로 각각 제시하시오.)'''

#for ~ in 리터럴
def addall(list):
    result = 0
    for x in list:
        result += x
    return result

print addall([1,2,3,4,5,6,7,8,9,10])


55


In [10]:
#리스트 리스트내포
def addall(list):
    return sum(x for x in list)

print addall([1,2,3,4,5,6,7,8,9,10])


55


In [11]:
#2) addallodd(list) 함수 (리스트내의 모든 홀수를 더하는 함수로서 해답으로는 for ~ in 리터럴과 리스트 내포 방식으로 각각 제시하시오.)
#for ~ in 리터럴
def addodd(list):
    result = 0
    for x in list:
        if x % 2 == 1:
            result += x
    return result

print addodd([1,2,3,4,5,6,7,8,9,10])

25


In [12]:
#리스트 리스트내포
def addodd(list):
    return sum(x for x in list if x%2)

print addodd([1,2,3,4,5,6,7,8,9,10])

25


1번째 함수는 간단하게 for문을 사용하여 해결하였고 리스트내포로 만든 addall() 함수는 내장함수인 sum()을 이용하여 한줄로 작성하였습니다. addodd()도 마찬가지로 2로 나누었을 때 1이 나오는 경우가 홀수 이므로 if문을 추가하여 간단하게 해결하였습니다.

In [13]:
L1 = [1, 2, 3]
L2 = [4, 5, 6]
d = {'low':L1, 'high':L2}
e = d
f = d.copy()
print d
print e
print f
print
d['low'] = [10, 20, 30]
d['high'][1] = 500
print d
print e
print f

{'high': [4, 5, 6], 'low': [1, 2, 3]}
{'high': [4, 5, 6], 'low': [1, 2, 3]}
{'high': [4, 5, 6], 'low': [1, 2, 3]}

{'high': [4, 500, 6], 'low': [10, 20, 30]}
{'high': [4, 500, 6], 'low': [10, 20, 30]}
{'high': [4, 500, 6], 'low': [1, 2, 3]}


1) 위 코드의 수행 결과 d와 e는 항상 같은 결과를 출력한다. 그 이유는 무엇인가?

e와 d는 서로 같은 주소를 공유하며 같은 객체를 가리키므로 객체의 값이 바뀌어도 같은 값을 출력합니다.

2) 위 코드의 수행 결과 마지막 f의 내용은 다음과 같다. 이 때 'high' 키의 값 내용 중 500이 출력된 이유와 'low' 키의 값 내용 중 [1, 2, 3]이 출력된 이유를 설명하시오 ([hint]: shallow copy 관점에서 설명하시오.)

f는d를 copy()즉 얕은 복사인 shallow copy를 한 것으로 같은 객체를 참조하되 다른 주소에서 그것을 참조하고 있습니다. 즉 d가 가리키는 리스트를 바꾼다면 d의 주소는 바뀐 리스트를 참조하지만 f의 주소값은 원래의 객체를 참조 하게 됩니다. 여기서 d가 가리키는 리스트의 원소를 바꾸게 되면 그 객체 내에서 바뀐 것 이기 때문에 f가 같이 가리키던 객체의 원소값이 바뀐 것 이기 때문에 f는 원소값이 바뀐 원래의 객체를 참조하게 됩니다.

In [48]:
'''사전 d = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5}가 주어졌을 때 다음 요구사항에 맞는 코드를 제시하시오
[참고]: d.keys(), d.values()를 통해 리스트를 얻어낸 후 리스트가 지니고 있는 sort(cmp=None, key=None, reverse=False)함수를 활용하시오.
1) 키의 알파벳 오름차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.
2) 키의 알파벳 내림차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.
3) 값의 오름차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.
4) 값의 내림차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.'''

d={'one':1,'two':2,'three':3,'four':4,'five':5}
L=[]
key = d.keys()
value = d.values()
for i in range(5):
    L.append((key[i], value[i]))
L.sort()
print L

[('five', 5), ('four', 4), ('one', 1), ('three', 3), ('two', 2)]


In [41]:
L.sort(reverse=True)
print L

[('two', 2), ('three', 3), ('one', 1), ('four', 4), ('five', 5)]


In [45]:
def mycmp(a ,b):
    return cmp(a[1],b[1])
L.sort(mycmp)
print L

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)]


In [47]:
L.sort(mycmp, reverse=True)
print L

[('five', 5), ('four', 4), ('three', 3), ('two', 2), ('one', 1)]


key와 value를 리스트화 하여 각각을 이용해 sort()를 이용해 풀려 하였으나 잘 안되어 다시 append()를 통해 튜플을 만들어 주었고 각 튜플의 첫 번째 원소는 키값이기 때문에 이것을 sort() 하여 오름차순으로 출력 하고 두 번째 출력할 때 에는  reverse=False 하여 내림차순으로 출력을 하여 줍니다. 그리고 mycamp()라는 함수를 사용해 튜플의 두 번째 원소 즉 value값을 반환하도록 함수를 구현하여 sort(mycamp)를 사용해 value값으로 정렬 하였습니다. 내림차순은 위와 같이 reverse=False를 사용 하였습니다

In [55]:
x=0
num=0
count=0
while x == 0:
    num+=1
    co = 0
    for n in range(1,num+1):
        if num %n ==0:
            co +=1
        if co >2:
                break
    if co ==2:
        count +=1
    if count ==10001:
        print num
        x=1


104743


처음과제에서 사용한 소수구하는 공식을 가져와 소수가 한 개 구해줄때마다 카운트를 올려 카운트가 10001이되면 while문을 종료하게 하였습니다.

In [58]:
'''다음은 연속된 1000자리 숫자입니다 (읽기 좋게 50자리씩 잘라놓음).

73167176531330624919225119674426574742355349194934
 96983520312774506326239578318016984801869478851843
 85861560789112949495459501737958331952853208805511
 12540698747158523863050715693290963295227443043557
 66896648950445244523161731856403098711121722383113
 62229893423380308135336276614282806444486645238749
 30358907296290491560440772390713810515859307960866
 70172427121883998797908792274921901699720888093776
 65727333001053367881220235421809751254540594752243
 52584907711670556013604839586446706324415722155397
 53697817977846174064955149290862569321978468622482
 83972241375657056057490261407972968652414535100474
 82166370484403199890008895243450658541227588666881
 16427171479924442928230863465674813919123162824586
 17866458359124566529476545682848912883142607690042
 24219022671055626321111109370544217506941658960408
 07198403850962455444362981230987879927244284909188
 84580156166097919133875499200524063689912560717606
 05886116467109405077541002256983155200055935729725
 71636269561882670428252483600823257530420752963450 

여기서 붉게 표시된 71112의 경우 7, 1, 1, 1, 2 각 숫자를 모두 곱하면 14가 됩니다.
이런 식으로 맨 처음 (7 × 3 × 1 × 6 × 7 = 882) 부터 맨 끝 (6 × 3 × 4 × 5 × 0 = 0) 까지 5자리 숫자들의 곱을 구할 수 있습니다.

이렇게 구할 수 있는 5자리 숫자의 곱 중에서 가장 큰 값은 얼마입니까?

'''

foo = "73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450"

sol2=0;
for i in range(len(foo)-4):
    sol = int(foo[i]) * int(foo[i+1]) * int(foo[i+2]) * int(foo[i+3]) * int(foo[i+4]) 

    if sol > sol2:
        sol2 = sol
print  sol2



40824


 1000자리의 숫자중 5자리씩 끊어서 곱하기 때문에 마지막 996번째 숫자까지를 for문을 돌려
줍니다. 이때 문자열이므로 int()를 써 정수형으로 바꾸어 줍니다. 각각 값이 sol로 저장되어 나올 때 sol2 보다 크면 sol2에 저장 해주는 식으로 마지막에 가장 큰 값은 sol2에 저장되어있습니다.

In [96]:
'''세 자연수 a, b, c 가 피타고라스 정리 a2 + b2 = c2 를 만족하면 피타고라스 수라고 부릅니다 (여기서 a < b < c ).
예를 들면 32 + 42 = 9 + 16 = 25 = 52이므로 3, 4, 5는 피타고라스 수입니다.

a + b + c = 1000  인 피타고라스 수 a, b, c는 한 가지 뿐입니다. 이 때, a × b × c 는 얼마입니까?'''
value=0

for a in range(1,1000):
    for b in range(1,1000):
        for c in range(1,1000):
            if (a ** 2) +(b ** 2) ==(c **2):
                if a+b+c==1000:
                    value = a*b*c

print value
                    

31875000


우선 3중 for문으로 a^2 + b^2 의 값이 c^2 이 되는 값을 찾고 그 값들 중 a,b,c의 합이 1000이 되는 숫자를 찾았습니다. 

In [94]:
#-*- coding: cp949-*-
#-*- coding: utf-8-*-
import urllib2
import string
source1 = urllib2.urlopen("http://cse.kut.ac.kr/").read()
source2 = urllib2.urlopen("http://www.naver.com/").read()
source3 = urllib2.urlopen("http://www.daum.net/").read()
source4 = urllib2.urlopen("http://www.nytimes.com/").read()


#print source # 추후 숙제 답안 제출 때엔 왼쪽 라인은 주석처리할 것
def parsing(source):
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(source)
    word = soup.text
    start = word.find('<')
    end = word.find('>')
    word = word[0:start] + word[end+1:]
    
    delet = string.punctuation
    for i in range(len(delet)):
        word = word.replace(delet[i],'')
    
    count = word.split()
    
    D={}
    for word in count:
        if word in D:
            D[word]+=1
        else:
            D[word]=1
        
    for key in D.keys():
        print "%s : %s" % (key, D[key]),;

    return ;

print '\n\n학부 학부홈페이지\n\n'

parsing(source1)
print '\n\n네이버\n\n'
parsing(source2)
print '\n\n다음\n\n'
parsing(source3)
print '\n\n뉴욕타임즈\n\n'
parsing(source4)
 



학부 학부홈페이지


1142 : 2 브라우저를 : 1 After : 1 【장학지원】보건복지심리재활분야 : 1 간 : 1 국민행복 : 1 Marissa : 1 산실로” : 1 1462 : 1 개최 : 1 제4차 : 1 Journalism : 1 있습니다 : 1 있는 : 1 공공장소에서 : 1 치열···10만원대 : 1 “스타트업은 : 1 전문연구요원 : 1 입학 : 1 구입 : 1 없습니다 : 1 수 : 3 접수 : 1 참여하세요 : 1 5X : 1 Plus : 1 동남구 : 2 출원 : 1 Big : 1 1940 : 2 모집 : 2 학과사무실 : 1 폐지 : 1 1549 : 2 투자유치 : 1 실무프로그래밍 : 1 Contact : 1 IDPW : 1 Xprize’s : 1 Hackathon : 1 2015 : 1 국회로 : 1 아이디 : 1 홈페이지에 : 1 국제전시회IoT : 1 경우 : 1 닫더라도 : 1 릴레이 : 1 국제적인 : 1 Copyright : 1 바로가기 : 2 20151020 : 9 Earnings : 1 Quick : 1 FAX : 1 신청 : 1 가입자 : 1 구성원소개 : 1 대한 : 1 홈커밍데이 : 1 1553 : 2 지원금 : 1 측면에서 : 1 New : 1 장학금 : 1 rights : 1 Mayer : 1 Misses : 1 에서 : 1 팁스타운 : 1 WEBMAIL : 1 ‘2015 : 1 CSE : 1 닷 : 1 Registration : 1 신청서 : 1 1412 : 2 Education : 1 20150930 : 1 이유 : 1 IT사업단 : 1 수준의 : 1 충절로 : 2 북부 : 1 천안시 : 2 Rep : 1 접속부터는 : 1 Empowerment : 1 졸업작품 : 1 Linkedin : 1 엔에스이 : 1 자료실 : 1 Exhibition : 1 기능을 : 1 4천이상 : 1 글로벌 : 3 전자신문 : 1 공지입니다 : 1 유지 : 2 Korea : 1 디스플레이장비전 : 1 for : 1 146014

저번과제를 불러와 구두문자를 제거 하기 위하여 여러 메소드를 써봣으나 잘 되지 않았고 replace()를 통해 구두문자를 제거하는 것이 최선이였고 string.punctuation를 통해 구두문자를 가져와 delet에 저장한후 for문으로 모든 구두문자를 replace로 지워 주었습니다.
그후 사전 D를 선언 하고 for문을 이용하여 단어가 처음 나오면 단어에 값을 1을 넣어주고 만약 나왔던 단어가 나오면 값에 +1을 해주는 형식으로 사전 D를 구성 하였습니다. 그후 for문을 이용해 key와 value를 출력하였습니다.
여러 홈페이지를 파싱해야 하기 때문에 다만들고 난뒤 모든 과정을 pasing()이라는 함수로 바꾸어 주었습니다.